map super+backspace send_text all \x17
map super+right send_text all \x05
map super+left send_text all \x01

shell_integration no-sudo 

hide_window_decorations titlebar-only

include themes.conf

cursor_shape block
cursor_blink_interval 0
shell_integration no-cursor no-title
window_padding_width 10

copy_on_select yes
macos_option_as_alt yes

font_size 12.75

foreground #a9b1d6
background #1a1b26

macos_titlebar_color background

color0  #414868
color8  #414868

color1  #f7768e
color9  #f7768e

color2  #73daca
color10 #73daca

color3  #e0af68
color11 #e0af68

color4  #7aa2f7
color12 #7aa2f7

color5  #bb9af7
color13 #bb9af7

color6  #7dcfff
color14 #7dcfff

color7  #c0caf5
color15 #c0caf5

cursor #c0caf5
cursor_text_color #1a1b26

selection_foreground none
selection_background #414868

url_color #9ece6a

active_border_color #7aa2f7
inactive_border_color #24283b
bell_border_color #e0af68

tab_bar_style fade
tab_fade 1
active_tab_foreground   #7aa2f7
active_tab_background   #1a1b26
active_tab_font_style   bold
inactive_tab_foreground #565f89
inactive_tab_background #24283b
inactive_tab_font_style bold
tab_bar_background #24283b

font_family  FuraCode Nerd Font

allow_remote_control yes
background_opacity 0.90
