#!/bin/bash

# Tokyo Night Storm palette
export TOKYO_BG_DARK=0xFF16161E
export TOKYO_BG=0xFF1A1B26
export TOKYO_SURFACE=0xFF24283B
export TOKYO_HOVER=0xFF292E42
export TOKYO_BORDER=0xFF7AA2F7
export TOKYO_BLUE=0xFF7AA2F7
export TOKYO_CYAN=0xFF7DCFFF
export TOKYO_EVENT=0xFFFF9E64
export TOKYO_FG=0xFFC0CAF5
export TOKYO_MUTED=0xFFA9B1D6
export TOKYO_COMMENT=0xFF565F89
export TOKYO_POPUP_BG=0xFA16161E
export TOKYO_POPUP_BORDER=0xFF343B58
export TOKYO_POPUP_ROW=0x0016161E
export TOKYO_POPUP_SELECTED=0xFF24283B
export TOKYO_POPUP_SEPARATOR=0xFF343B58
export TOKYO_POPUP_SHADOW=0x80000000
export TOKYO_GREEN=0xFF9ECE6A

# Compatibility names used throughout the existing plugins
export PURPLE=$TOKYO_BLUE
export GREY=$TOKYO_COMMENT
export TRANSPARENT=0x00000000
export WHITE=$TOKYO_FG
export BLUE=$TOKYO_BLUE
export MAGENTA=0xFFBB9AF7
export ORANGE=0xFFFF9E64
export TEMPUS=$TOKYO_BG
export STATUS=$TOKYO_SURFACE
export SPACEBG=0xAA7AA2F7
export MIDNIGHT=$TOKYO_BG

# Pac-Man stays optically white through every animation frame.
export PACMAN_WHITE=0xFFFFFFFF
export PACMAN_YELLOW=$PACMAN_WHITE
export PACMAN_BG=$TRANSPARENT
export PACMAN_TRAIL=$TRANSPARENT
export PACMAN_BORDER=$TRANSPARENT
export GHOST_RED=0xFFF7768E
export GHOST_PINK=0xFFBB9AF7
export GHOST_CYAN=$TOKYO_CYAN
export GHOST_ORANGE=$ORANGE
export SUBTEXT=$TOKYO_MUTED
export APP_FADE=0x003B4261
