#!/bin/bash

#                      _ _
#                     (_) |
#  _ __ _____   ___ __ _| |_ ____           github:     https://github.com/mvritz
# | '_ ` _ \ \ / / '__| | __|_  /           twitter:    https://twitter.com/meshtonight
# | | | | | \ V /| |  | | |_ / /            website:    https://moriware.com
# |_| |_| |_|\_/ |_|  |_|\__/___|
#

source "$HOME/.config/sketchybar/colors.sh"
source "$HOME/.config/sketchybar/icons.sh"
source "$HOME/.config/sketchybar/environment.sh"

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"
POPUP_CLICK_SCRIPT="$PLUGIN_DIR/popup_toggle.sh"
ACTIVE_SPACE=$(yabai -m query --spaces --space | jq '.index')
rm -f "${TMPDIR:-/tmp}/sketchybar-pacman/front-context"

bar=(
  height=30
  margin=5
  corner_radius=10
  position=top
  color="$TRANSPARENT"
  border_color="$TOKYO_BORDER"
  y_offset=4
  sticky=off
)

sketchybar --bar "${bar[@]!}"

defaults=(
  updates=when_shown
  icon.drawing=on
  icon.font="SF Pro:Regular:12.0"
  icon.color="$WHITE"
  label.font="SF Pro:Regular:12.0"
  label.drawing=on
  label.color="$WHITE"
  popup.background.color="$TOKYO_POPUP_BG"
  popup.background.corner_radius=10
  popup.background.border_width=1
  popup.background.border_color="$TOKYO_POPUP_BORDER"
  popup.background.padding_left=7
  popup.background.padding_right=7
  popup.background.shadow.drawing=on
  popup.background.shadow.color="$TOKYO_POPUP_SHADOW"
  popup.background.shadow.angle=270
  popup.background.shadow.distance=6
  popup.blur_radius=36
)

sketchybar --default "${defaults[@]!}"
sketchybar --add event window_context_changed

time=(
  update_freq=1
  script="$PLUGIN_DIR/time.sh"
  click_script="$POPUP_CLICK_SCRIPT"
  popup.align=right
  popup.height=32
  popup.y_offset=8
  label.font="SF Pro:Bold:12.0"
  label.padding_left=20
  label.padding_right=15
  background.corner_radius=10
  background.color="$TOKYO_BG"
  background.height=19
  background.padding_left=-10
  background.padding_right=3
  background.border_color="$TOKYO_BORDER"
)

sketchybar --add item time right \
  --set time "${time[@]!}" \
  --subscribe time system_woke mouse.entered mouse.exited

date=(
  update_freq=30
  script="$PLUGIN_DIR/date.sh"
  label.padding_left=15
  background.color="$TOKYO_BG"
  background.height=19
  background.corner_radius=10
)

sketchybar --add item date right \
  --set date "${date[@]!}" \
  --subscribe date system_woke

wifi=(
  script="$PLUGIN_DIR/wifi.sh"
  click_script="$POPUP_CLICK_SCRIPT"
  popup.align=center
  popup.height=32
  popup.y_offset=8
  width=33
  label.width=33
  label.align=center
  label.padding_right=0
  update_freq=60
)

rm -f /tmp/sketchybar_wifi
sketchybar --add item wifi right \
  --set wifi "${wifi[@]!}" \
  --subscribe wifi system_woke mouse.entered mouse.exited

battery=(
  script="$PLUGIN_DIR/battery.sh"
  update_freq=120
  updates=on
  click_script="$POPUP_CLICK_SCRIPT"
  popup.align=center
  popup.height=32
  popup.y_offset=8
  width=33
  icon.width=33
  icon.align=center
  label.padding_left=0
)

sketchybar --add item battery right \
  --set battery "${battery[@]!}" \
  --subscribe battery power_source_change system_woke mouse.entered mouse.exited

volume_icon=(
  script="$PLUGIN_DIR/volume.sh"
  click_script="$PLUGIN_DIR/volume_click.sh"
  label="$VOLUME_66"
  popup.align=center
  popup.height=32
  popup.y_offset=8
  width=33
  label.width=33
  label.align=center
  label.padding_right=0
  label.padding_left=0
)

sketchybar --add item volume_icon right \
  --set volume_icon "${volume_icon[@]!}" \
  --subscribe volume_icon volume_change mouse.entered mouse.exited

weather=(
  background.color="$TOKYO_SURFACE"
  background.height=25
  background.corner_radius=10
  background.padding_right=10
  background.border_color="$TOKYO_BORDER"
  background.border_width=2
  icon.padding_left=15
  icon.padding_right=15
  update_freq=900
  script="$PLUGIN_DIR/weather.sh"
  click_script="$POPUP_CLICK_SCRIPT"
  popup.align=center
  popup.height=34
  popup.y_offset=8
)

sketchybar --add item weather right \
  --set weather "${weather[@]!}" \
  --subscribe weather mouse.entered mouse.exited

#spotify=(
#  click_script="$POPUP_CLICK_SCRIPT"
#  popup.horizontal=on
#  popup.align=center
#  popup.height=100
#  icon="$SPOTIFY"
#  icon.padding_right=15
#  icon.padding_left=15
#  background.color="$TEMPUS"
#  background.height=19
#  background.corner_radius=10
#  background.padding_left=3
#  background.padding_right=3
#  script="$PLUGIN_DIR/spotify.sh"
#  update_freq=5
#)
#
#sketchybar --add event spotify_change $SPOTIFY_EVENT \
#    --add item spotify e \
#    --set spotify "${spotify[@]!}" \
#    --subscribe spotify mouse.entered mouse.exited \
#    mouse.exited.global
#
#spotify_label=(
#  label="Spotify"
#  label.padding_left=6
#  label.padding_right=13
#  label.font="SF Pro:Bold:9.0"
#  label.drawing=on
#  script="$PLUGIN_DIR/spotify.sh"
#  update_freq=5
#  background.padding_right=3
#  width=0
#)
#
#sketchybar --add item spotify_label e \
#  --set spotify_label "${spotify_label[@]!}"

#ram=(
#  icon="$RAM"
#  icon.padding_left=15
#  script="$PLUGIN_DIR/ram.sh"
#  label.padding_right=15
#  label.padding_left=10
#  update_freq=60
#  background.corner_radius=10
#  background.color="$TEMPUS"
#  background.height=19
#  background.padding_left=-6
#  background.padding_right=3
#  background.border_color="$PURPLE"
#)
#
#sketchybar --add item ram q \
#  --set ram "${ram[@]!}"
#
#cpu=(
#  icon="$CPU"
#  icon.padding_left=15
#  script="$PLUGIN_DIR/cpu.sh"
#  label.padding_left=10
#  label.padding_right=15
#  update_freq=60
#)
#
#sketchybar --add item cpu q \
#  --set cpu "${cpu[@]!}"

apple=(
  script="$PLUGIN_DIR/apple.sh"
  click_script="$POPUP_CLICK_SCRIPT"
  popup.align=left
  popup.height=32
  popup.y_offset=8
  label="$APPLE"
  label.padding_right=15
  label.padding_left=15
  background.color="$TOKYO_BG"
  background.height=19
  background.corner_radius=10
  background.padding_left=3
  background.padding_right=3
)

sketchybar --add item apple left \
  --set apple "${apple[@]!}" \
  --subscribe apple mouse.entered mouse.exited

space=(
  label.drawing=off
  width=30
  icon.font="SF Pro:Bold:14.0"
  icon.width=30
  icon.align=center
  icon.padding_left=0
  icon.padding_right=0
  background.color="$TRANSPARENT"
  background.height=18
  background.corner_radius=9
  background.border_width=1
  background.border_color="$TRANSPARENT"
)

declare -a spacesArray=()
for i in "${!SPACE_GHOSTS[@]}"; do
  sid=$(($i + 1))

  if [[ $sid -eq $ACTIVE_SPACE ]]; then
    CURRENT_ICON=$PACMAN
    CURRENT_COLOR=$PACMAN_WHITE
    CURRENT_BG=$TRANSPARENT
    CURRENT_BORDER=$TRANSPARENT
  else
    CURRENT_ICON=${SPACE_GHOSTS["$i"]}
    CURRENT_COLOR=${SPACE_GHOST_COLORS["$i"]}
    CURRENT_BG=$TRANSPARENT
    CURRENT_BORDER=$TRANSPARENT
  fi

  spacesArray+=("space.$sid")

  sketchybar --add space space.$sid left \
    --set space.$sid space=$sid \
    icon="$CURRENT_ICON" \
    icon.color="$CURRENT_COLOR" \
    background.color="$CURRENT_BG" \
    background.border_color="$CURRENT_BORDER" \
    click_script="yabai -m space --focus $sid" \
    script="$PLUGIN_DIR/space_hover.sh" \
    "${space[@]}" \
    --subscribe "space.$sid" mouse.entered mouse.exited
done

sketchybar --add item space_animator left \
  --set space_animator drawing=off updates=on script="$PLUGIN_DIR/spaces.sh" \
  --subscribe space_animator space_change

front_app=(
  script="$PLUGIN_DIR/front_app.sh"
  update_freq=5
  updates=on
  scroll_texts=off
  padding_left=8
  icon="Desktop"
  icon.font="SF Pro:Semibold:11.0"
  icon.color="$TOKYO_BLUE"
  icon.padding_left=11
  icon.padding_right=11
  label=""
  label.font="SF Pro:Medium:11.0"
  label.color="$SUBTEXT"
  label.max_chars=38
  label.padding_left=0
  label.padding_right=0
  background.color="$TOKYO_SURFACE"
  background.height=25
  background.corner_radius=9
  background.border_color="$TOKYO_BORDER"
  background.border_width=2
)

sketchybar --add item front_app left \
  --set front_app "${front_app[@]!}" \
  --subscribe front_app front_app_switched space_change window_context_changed

brackets=(
  background.color="$TOKYO_SURFACE"
  background.height=25
  background.corner_radius=10
  background.border_color="$TOKYO_BORDER"
  background.border_width=2
)

sketchybar --add bracket status time date wifi battery volume_icon right \
  --set status "${brackets[@]!}"

#sketchybar --add bracket music spotify spotify_label e \
#   --set music "${brackets[@]!}" \
#   background.padding_right=50

#sketchybar --add bracket utilis ram cpu q \
#  --set utilis "${brackets[@]!}" \
#  background.padding_left=50

sketchybar --add bracket control apple "${spacesArray[@]!}" center \
  --set control "${brackets[@]!}"


sketchybar --update
