#!/bin/sh

MAIN_DISPLAY=$(system_profiler SPDisplaysDataType | grep -B 3 'Main Display:' | awk '/Display Type/ {print $3}')

config=(
  mouse_follows_focus off
  focus_follows_mouse autoraise
  window_origin_display default
  window_placement second_child
  window_zoom_persist on
  window_topmost off
  window_shadow on
  window_animation_frame_rate 180
  window_animation_duration 0.3
  window_animation_easing
  window_opacity_duration 0.11
  active_window_opacity 1.0
  normal_window_opacity 0.94
  window_opacity off
  insert_feedback_color 0xffd75f5f
  split_ratio 0.50
  split_type auto
  auto_balance on
  left_padding 12
  right_padding 12
  top_padding 5
  bottom_padding 10
  window_gap 5
  layout bsp
  mouse_modifier cmd
  mouse_action1 move
  mouse_action2 resize
  mouse_drop_action swap
)

yabai -m config ${config[@]}

borders active_color=0xFFC099FF inactive_color=0xFF444A73 width=5.0 &

yabai --load-sa

if [[ $MAIN_DISPLAY = "Built-in" ]]; then
    yabai -m config external_bar main:5:0
else
    yabai -m config external_bar main:30:0
fi

yabai -m rule --add app="^System Settings" sticky=on manage=off
yabai -m rule --add app="^Finder" sticky=on manage=off
yabai -m rule --add app="^WhatsApp" sticky=on manage=off
yabai -m rule --add app="^Facetime" sticky=on manage=off
yabai -m rule --add app="^Raycast" sticky=on manage=off
yabai -m rule --add app="^Music" sticky=on manage=off
yabai -m rule --add app="^Reminders" sticky=on manage=off

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=space_changed action="/Users/moritzdresch/.config/sketchybar/plugins/spaces.sh"

