#!/bin/bash

# focus respective space
alt - d : yabai -m space --focus 1
alt - w : yabai -m space --focus 2
alt - u : yabai -m space --focus 3
alt - m : yabai -m space --focus 4
alt - e : yabai -m space --focus 5
alt - g : yabai -m space --focus 6

# increase or decrease window size
alt - h : yabai -m window --resize left:-50:0 ; yabai -m window --resize right:-50:0
alt - l : yabai -m window --resize right:50:0 ; yabai -m window --resize left:50:0

# make current application fullscreen
alt - f : yabai -m window --toggle zoom-fullscreen

# rotate current application
alt - r : yabai -m space --rotate 90

# restart yabai
alt - a : yabai --restart-service

# reload sketchybar
alt - s : brew services restart sketchybar
