#!/bin/bash

options=(
	style=round
	width=4.0
	hidpi=on
	order=above
	active_color="gradient(top_left=0xFF7AA2F7,bottom_right=0xFFBB9AF7)"
	inactive_color=0x66565F89
	blacklist="iPhone Mirroring"
)

exec /opt/homebrew/bin/borders "${options[@]}"
